wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpaper List/Advent10.jpg
    fit_mode = cover
    timeout = 3600
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpaper List/Ever Crisis Tifa non Watermarked.jpg
    fit_mode = cover
    timeout = 3600
}