# preload = ~/Pictures/Wallpapers/My Artworks/tifa_v0.13.jpg
# splash = false

# wallpaper {
#     monitor = eDP-1
#     path = ~/Pictures/Wallpapers/My Artworks/tifa_v0.13.jpg
#     fit_mode = cover
#     # timeout = 3600
# }

preload = ~/.config/hypr/ffviiec_x_nier.jpg
splash = false

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/ffviiec_x_nier.jpg
    fit_mode = cover
}
