wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/My Artworks/tifa_v0.18.jpg
    fit_mode = cover
    # timeout = 3600
}

# wallpaper {
#     monitor = eDP-1
#     path = ~/Pictures/Wallpaper List/Ever Crisis Tifa non Watermarked.jpg
#     fit_mode = cover
#     timeout = 3600
# }

splash = false